### ISSUE TITLE
Syntax: option values with arrays are not supported

### ISSUE THREAD

**Issue by nomaed** [devkanro/intellij-protobuf-plugin#25]
It looks like option values that are arrays are not supported, and are displayed as invalid syntax. This often breaks the entire file and also auto-formatting doesn't work.

Example from the internet:
```protobuf
message MyMeta {
    int32 id = 1 [(com.util.meta) = {
        needValidation: false,
        fileMap: [
            {
                key: "t",
                value: "raw_orders"
            }
        ];
    }];
}
```
This should be a valid protobuf option, however this how it looks actually:
<img width="448" alt="Screen Shot 2021-07-04 at 10 22 29" src="https://user-images.githubusercontent.com/9551921/124376963-20f2bb00-dcb2-11eb-8243-3b36360de49d.png">

**Comment by devkanro** [comment]
There is no array in the `MessageValue` rule.

Maybe you should try to set it again(repeated field): 
```protobuf
message MyMeta {
    int32 id = 1 [(com.util.meta) = {
        needValidation: false,
        fileMap: {
            key: "t",
            value: "raw_orders"
        },
        fileMap: {
            key: "key2",
            value: "otherValue"
        }
    }];
}
```

**Comment by devkanro** [comment]
There are no many documents for protobuf option, I just use `protoc` to compile those protos, after my test, `protoc` can accept both of them, but my plugin only supports the **repeated syntax**.

I will add array syntax support in the next version.

**Comment by nomaed** [comment]
You are right about not much documentation. I was looking for a while to see if this syntax even valid. But I did find it being used in a bunch of places eventually, and I saw that the native IntelliJ plugin does support it well, so I figured it is something that is worth having in your (excellent) plugin too.

Thank you!

**Comment by devkanro** [comment]
I have added array syntax support in commit f211f6d5208092ecb64802a1e7bdc27429fe3b72.

But I got some problems releasing it, check the issue JetBrains/gradle-intellij-plugin#721 to get more details.

There is the local install package, maybe you can help me to test it before the CI work.

[IntelliJ Protobuf Language Plugin-1.4.1-EAP.zip](https://github.com/devkanro/intellij-protobuf-plugin/files/6763550/IntelliJ.Protobuf.Language.Plugin-1.4.1-EAP.zip)

**Comment by devkanro** [comment]
Fixed in release [1.4.1-EAP](https://github.com/devkanro/intellij-protobuf-plugin/releases/tag/v1.4.1-EAP)

**Comment by jvolkman** [comment]
The option syntax is just the protobuf text format. It's not well documented, but `protoc` supports anything that's supported by [`text_format.cc`](https://github.com/protocolbuffers/protobuf/blob/master/src/google/protobuf/text_format.cc). For example, even this special syntax for `Any` values is supported: 

```protobuf
syntax = "proto3";
import "google/protobuf/descriptor.proto";
import "google/protobuf/any.proto";

package foo.bar;

message MyType {
  repeated google.protobuf.Any any = 1;
  bool value = 2;
}

message AnyType1 {
  google.protobuf.Any any = 1;
  string foo = 2;
}

message AnyType2 {
  google.protobuf.Any any = 1;
  string bar = 2;
}

extend google.protobuf.FileOptions {
  MyType opt = 2000;
}

option (opt) = {
  any {
    [type.googleapis.com/foo.bar.AnyType1] {
      foo: "foo"
      any {
        [type.googleapis.com/foo.bar.AnyType2] {
          bar: "bar"
        }
      }
    }
  }
};
```

**Comment by devkanro** [comment]
Thanks for your information, I will try to add prototext support in the next version.

**Comment by devkanro** [comment]
@jvolkman 
Do you own write access permission to your plugin after JetBrains adopts it?
I'm a little curious about the way you work with JetBrains.

**Comment by jvolkman** [comment]
> @jvolkman
> Do you own write access permission to your plugin after JetBrains adopts it?
> I'm a little curious about the way you work with JetBrains.

I still have access to the marketplace entry but not the intellij-plugins repository. I would need to submit PRs.
